# Generated by Django 3.2 on 2024-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('CE', 'Connection Error'), ('TPF', 'Third Party Fail'), ('LB', 'Low Balance'), ('SE', 'System Error')], help_text='Reason why trasnaction faild.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retry',
            field=models.IntegerField(default=5),
        ),
    ]
